version: '2'
services:
  fpm:
    build: PHP7fpm
    restart: never
    volumes:
      - ./app:/var/www/html

    ports:
      - "9000:9000"

  nginx:
    build: Nginx
    restart: never
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm
