version: "2"
services:
  api:
    build: ./PHP7
    restart: always
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    links:
      - mongo

  mongo:
    image: mongo:3.0.4
    ports:
     - "27017:27017"
    volumes:
     - './mongodata:/data/db'
